services:
  backend:
    volumes:
      - ./backend:/usr/src/app           # Mount the folder with package.json
      - .backend/node_modules:/usr/src/app/node_modules        # Keep container's node_modules
    command: sh -c "npx nodemon index.js"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./primary-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./primary-app:/usr/src/app       # Mount the folder with package.json
      - /usr/src/app/node_modules
    command: sh -c "npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true         # Helps file watching inside Docker
      - NODE_ENV=development