services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"  # Host port 3307 → Container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootdev04061997!
      MYSQL_DATABASE: profiledata
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p $${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend           # Dockerfile lives here
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mysql # Ensure MySQL starts before backend
    ports:
      - "8800:8800"
    env_file:
      - ./backend/.env            # Loads backend-specific env vars
    
    volumes:
      - ./backend:/usr/src/app  # Mounts actual backend code
      - /usr/src/app/node_modules  # Prevent overwriting node_modules in container
    restart: unless-stopped

  frontend:
    build:
      context: ./primary-app          # Dockerfile lives here
      dockerfile: Dockerfile.dev
    container_name: primary-app
    ports:
      - "3000:3000"
    env_file:
      - ./primary-app/.env        # Loads frontend-specific env vars
    depends_on:
      - backend
    volumes:
      - ./primary-app:/usr/src/app  # Mounts actual frontend code
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  mysql-data: