services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootdev04061997!
      MYSQL_DATABASE: profiledata
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    depends_on:
      mysql: # Ensure MySQL starts before backend
        condition: service_healthy
    build:
      context: ./backend           # Dockerfile lives here
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8800:8800"
    env_file:
      - ./backend/.env            # Loads backend-specific env vars
    volumes:
      - ./backend:/usr/src/app  # Mounts actual backend code
      - /usr/src/app/node_modules  # Prevent overwriting node_modules in container
    restart: unless-stopped

  frontend:
    build:
      context: ./primary-app          # Dockerfile lives here
      dockerfile: Dockerfile.dev
    container_name: primary-app
    ports:
      - "3000:3000"
    env_file:
      - ./primary-app/.env        # Loads frontend-specific env vars
    depends_on:
      - backend
    volumes:
      - ./primary-app:/usr/src/app  # Mounts actual frontend code
      - /usr/src/app/node_modules
    restart: unless-stopped

volumes:
  mysql-data: